### ISSUE TITLE
About page: Uneven alignment 

### ISSUE THREAD

**Issue by jennyxxdance** [cmu-delphi/www-main#79] opened 2020-11-20 20:07 UTC
This [about page](https://cmu-delphi-main.netlify.app/about/) has uneven alignment. <img width="1440" alt="Screen Shot 2020-11-20 at 3 05 30 PM" src="https://user-images.githubusercontent.com/66391749/99844970-e9c80300-2b41-11eb-9488-4140224c0d77.png">
Here's our [link to figma doc](https://www.figma.com/file/IiYu74VmEi4GVS4bnYaTd6/Delphi-Site-Redesign?node-id=642%3A2584) with fixed alignment
<img width="658" alt="Screen Shot 2020-11-20 at 3 06 42 PM" src="https://user-images.githubusercontent.com/66391749/99845114-1ed45580-2b42-11eb-92b0-2cb444d09ea5.png">

**Comment by sgratzl** [comment] 2020-11-23 13:37
duplicate of #78

**Comment by tildechris** [comment] 2020-11-24 17:43
Closing as duplicate of #78.

**Closed** 2020-11-24 17:43 UTC
Labels: enhancement
